# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/DSDLabs/Blinky/Blinky.cache/wt [current_project]
set_property parent.project_path D:/DSDLabs/Blinky/Blinky.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib D:/DSDLabs/Blinky/Blinky.srcs/sources_1/new/Blinky.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/DSDLabs/Blinky/Blinky.srcs/constrs_1/new/blinky.xdc
set_property used_in_implementation false [get_files D:/DSDLabs/Blinky/Blinky.srcs/constrs_1/new/blinky.xdc]


synth_design -top Blinky_1Hz -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Blinky_1Hz.dcp

catch { report_utilization -file Blinky_1Hz_utilization_synth.rpt -pb Blinky_1Hz_utilization_synth.pb }
